### ISSUE TITLE
Requested Features:

### ISSUE THREAD

**Issue by drhirsch** [scivision/lowtran#1]
[Kelly of SAIC requests](https://scivision.co/f2py-running-fortran-code-in-python-on-windows/) Object to Sensor configuration, instead of the Sensor-Sun configuration I have first setup the code with.

My program does not write TAPE files, it directly injects into the Fortran variables. In particular, I didn't like how LOWTRAN7 read TAPE5, it was really easy to screw up on the number of whitespaces used and get an unexpected result.
## I think we need to think how a Pythonic interface to Lowtran should look. We could hack on this specific case Kelly requests, I'm fine with that too. I am not out to recreate a GUI like MODTRAN, but am fine with that.

object-sensor scheme, given:
object position ECI
sensor position ECI
date and time
geography map for land sea level

The program computes the lat-lon-alt object & sensor positions, position of sun, moon, the season, land influence, etc.
The most general case possible. Aerosols, stratospherics, weather, etc. are user inputs.

Then writes TAPE5, runs the exe, extracts data, calculates info, draws graphs of:
transmission
radiance
absorption coefficients
plots

Ah, something like PCModWin:

http://www.ontar.com/Software/ProductDetails.aspx?item=PcModWin

**Comment by scivision** [comment]
This has been implemented in the user scripts.
