### ISSUE TITLE
Can't run example code

### ISSUE THREAD

**Issue by OctagonHex** [scivision/lowtran#3]
Dear all,
I got through the setup on windows 7 x64.
I'm using Anaconda 3.5.10
I succeeded in compiling the fortran code with minGW-x86_64 7.2.0 release-posix-seh-rt_v5-rev0
But when I try to start any of the examples, I get this error
```

Traceback (most recent call last):
  File "TransmittanceGround2Space.py", line 25, in <module>
    TR = lowtran.loopangle(c1)
  File "C:\lowtran-2.2\lowtran\__init__.py", line 84, in loopangle
    TR.loc[a, ...] = T
  File "C:\Anaconda3\lib\site-packages\xarray\core\dataarray.py", line 112, in __setitem__
    self.data_array[pos_indexers] = value
  File "C:\Anaconda3\lib\site-packages\xarray\core\dataarray.py", line 484, in __setitem__
    assert_coordinate_consistent(value, obj.coords.variables)
  File "C:\Anaconda3\lib\site-packages\xarray\core\coordinates.py", line 325, in assert_coordinate_consistent
    .format(k, obj[k], coords[k]))
IndexError: dimension coordinate 'wavelength_nm' conflicts between indexed and indexing objects:
<xarray.DataArray 'wavelength_nm' (wavelength_nm: 9935)>
array([30303.03   , 29850.746  , 29411.764  , ...,   200.04001,   200.02   ,
         200.     ], dtype=float32)
Coordinates:
  * wavelength_nm  (wavelength_nm) float32 30303.03 29850.746 29411.764 ...
vs.
<xarray.IndexVariable 'wavelength_nm' (wavelength_nm: 9935)>
array([30000.      , 29556.650246, 29126.213592, ...,   200.02667 ,
         200.006667,   199.986668])

```

**Comment by scivision** [comment]
OK for Windows I only test the Fortran code standalone. 
On Linux, I am able to run that example that doesn't work for you, and have added the plot to the Readme in the "develop" branch.
I did find a couple other glitches in the top level *.py example scripts, I'll fix them in "develop" branch and merge to master. Thank you for your report!

**Comment by scivision** [comment]
I will try to add some assert statements to watch for or at least help debug this issue. I run into issues where Windows compilation rounds quite differently than Mac/Linux compilers, even using the same gfortran compiler. Thank you!

**Comment by scivision** [comment]
Yes I see the issue myself, it is an inadvisable use of coordinates. I need to update the code to fix this, previously, my test coverage did not handle this case, but now it does, so while I don't see it on my PC, I do see it even on other Linux PCs as well.

**Comment by scivision** [comment]
This bug was correct by cleaning up and correcting the API.

You can use .squeeze() on the output arrays to eliminate singleton dimensions if you so wish.
