### ISSUE TITLE
Documentation: Details for horizontal path

### ISSUE THREAD

**Issue by OctagonHex** [scivision/lowtran#5]
Hello,
this more a request for help on the documentation. I studied the original "LOWTRAN7 User Manual" that is conveniently linked on the main page, but I'm none the wiser...
I would like to calculate a horizontal path transmittance, so I use the file UserDataHorizontalTransmittance.py as a good starting point.
In there, the LOWTRAN variables range_km, zmdl & h1  are assigned the value of obsalt (observer altitude), but this shows up as "path length 0.05km" in the plot. I checked the manual an on PDF page 40 it says:
ZMDL = Altitude of layer boundary (km)  
P = Pressure of layer boundary
T = Temperature of layer boundary

So now I'm at a complete loss on how to achieve a simple calculation like this:
initial altitude (H1) = 300 meter above see level
final altitude (seems like this is called H2) = 300 meter above see level
path length = 1000 meter

I would be very happy, if you could shed some light on this!

**Comment by scivision** [comment]
I simplified this example by having it use Lowtran's atmosphere models and I fixed the altitude vs. range specification, in HorizontalTransmittance.py.
When developing it's best to "install" via git clone, `pip install -e .`  and then every change is reflected immediately in your next Python import.

**Comment by OctagonHex** [comment]
Thank you!
That will help me to modify the script to my needs. 
Unfortunately, you removed the original UserDataHorizontalTransmittance.py where I could specify the climate condition in my user-script, instead of editing it in the __init__.py which is rather non-intuitive.

**Comment by scivision** [comment]
I'd rather not edit in __init__.py, I would like to make that more object-oriented, where a user script calls predefined scenario types.
I have added two scripts: one for "plain" Lowtran horizontal, and another for "user-defined atmosphere" horizontal.
Additonal cases may well be desired, but I think we can do it through an extensible object-oriented paradigm, where simple user scripts call particular Lowtran scenarios.
