### ISSUE TITLE
Setting wavelength interval

### ISSUE THREAD

**Issue by SamanthaFassnacht** [scivision/lowtran#6]
Currently, when running a function from Lowtran many times within a python file, it takes a substantial amount of time to get results. To speed this process up, within my installed copy of Lowtran, I have manually manipulated the wavenumber sampling interval (called wlcminvstep) within the wavelength conversion function nm2lt7. It seems to me that there is currently no way to alter the sampling interval from calling functions within Lowtran. 

It would be very helpful to allow users to input their own sampling interval along with the wavelength starting and stopping points, as the current low resolution may be too fine for certain uses, especially if multiple calls to the Lowtran functions need to be executed within a python script.

**Comment by scivision** [comment]
Yes I agree, this is done in https://github.com/scivision/lowtran/releases/tag/v2.4.0
