### ISSUE TITLE
how to get  Atmospheric correction image

### ISSUE THREAD

**Issue by SmithPeng** [scivision/lowtran#7]
I tried to use lowtran model to get atmospherically-correct satellite images ,such as Landsat / sentinel-2A .
 [ARCSI](https://www.arcsi.remotesensing.info/index.html) could  be used to get atmospherically-correct images results , and a scene image used about 8 minute ,which is too slow.
So, I look forward to trying lowtran for the same purpose, but I don't know how to use lowtran and have no tutorials.
Can anyone help me or show me the procedures.

**Comment by scivision** [comment]
Hi Smith, that would take some software infrastructure beyond what Lowtran provides. It provides point-to-point simulations of spectrally depended absorption, irradiance, etc. So it would be some weeks of effort to do this, by someone reasonably expert in the field.
