### ISSUE TITLE
Install directions for systems with python 2 & 3

### ISSUE THREAD

**Issue by jimparker96313** [scivision/lowtran#8]
Hello,
  Thank you for providing this code.  I have just a comment that might help future users who wish to use the code if they try to follow your install directions and have both python 2.7 (default) and python 3.6+ installed (common on many current distros).  

Ensure they install via their distro package system
<python3>
<python3-dev>
<python3-pip>

and install lowtran with 
<pip3 install -e .>

**Comment by jimparker96313** [comment]
Ok,
  That didn't save my comment as desired...

Should be  "Ensure they install via their distro package system
python3
python3-dev
python3-pip

and install lowtran with 
pip3 install -e .

**Comment by scivision** [comment]
Hi Jim,
Normally I recommend NOT installing with system Python, because some packages do not install safely and can corrupt system Python, possibly as bad as needing to reinstall the whole operating system.

So generally we recommend the 50 MB [Miniconda Python](https://conda.io/miniconda.html)
